Raise required compiler to Rust 1.75
On older compilers, the pointer cast does not compile due to a rustc bug.

    error[E0310]: the parameter type `T` may not live long enough
       --> src/lib.rs:223:12
        |
    223 |         &*(&phantom_data as *const dyn NonStaticAny as *const (dyn NonStaticAny + 'static))
        |            ^^^^^^^^^^^^^ ...so that the type `T` will meet its required lifetime bounds
        |
    help: consider adding an explicit lifetime bound...
        |
    203 |     T: ?Sized + 'static,
        |               +++++++++